[package]
name = "ecs-test-game"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ggez = "0.7.0"
legion = "0.4.0"
rand = "*"
egui = "0.18.1"
ggez-egui = "0.2.1"
glam = { version = "0.20"}