[package]
name = "ecs_test_game"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ggez = "0.7.0"
legion = "0.4.0"
rand = "*"
egui = "0.18.1"
ggez-egui = "0.2.1"
glam = { version = "0.20"}
criterion = { version = "0.4.0", features = ["html_reports", "plotters"] }
heapsize = "0.4.2"
sqlite = "0.27.3"
#jemallocator = "0.5"
#jemalloc-sys = {version = "0.5", features = ["stats"]}
#libc = "0.2"
#duckdb = {version = "0.5.1", features = ["bundled"]}

[[bench]]
name = "benchmarks"
harness = false

